### ISSUE TITLE
[ENH]: Education timeline

### ISSUE THREAD

**Issue by epicman25** [2KAbhishek/2kabhishek.github.io#15]
### Description

I observed that css file has components related to an education timeline.But I couldn't find any html code related to that.Can you provide html code for education timeline.It will be helpful for freshers.

**Comment by 2KAbhishek** [comment]
Thanks for bringing up the issue, I actually recently removed the education and projects block, check the [legacy branch](https://github.com/2KAbhishek/2kabhishek.github.io/tree/legacy).

**Comment by epicman25** [comment]
Thank you.
